on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: Compile CSS from SCSS files
      uses: gha-utilities/sass-build@v0.4.7
      with:
        source: assets/sass/style.scss
        destination: assets/css/style.css

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.cctt.vn
        username: ftp_acc_github@cctt.vn
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /wp-content/themes/cinemart/